<?php
session_start();
require 'connect.php';


       
		$id_num = mysqli_real_escape_string($condb,$_POST['id_num']);
		$name = mysqli_real_escape_string($condb,$_POST['name']);
		$salary = mysqli_real_escape_string($condb,$_POST['salary']);
		$tax = mysqli_real_escape_string($condb,$_POST['tax']);
		$assur_dd = mysqli_real_escape_string($condb,$_POST['assur_dd']);
		$saving = mysqli_real_escape_string($condb,$_POST['saving']);
		$kid = mysqli_real_escape_string($condb,$_POST['kid']);
		$gpf = mysqli_real_escape_string($condb,$_POST['gpf']);
		$pfund = mysqli_real_escape_string($condb,$_POST['pfund']);
		$soc = mysqli_real_escape_string($condb,$_POST['soc']);
		$total = mysqli_real_escape_string($condb,$_POST['total']);
		$type1 = mysqli_real_escape_string($condb,$_POST['type1']);
		$type2 = mysqli_real_escape_string($condb,$_POST['type2']);
		$type3 = mysqli_real_escape_string($condb,$_POST['type3']);
		$type4 = mysqli_real_escape_string($condb,$_POST['type4']);
		$type5 = mysqli_real_escape_string($condb,$_POST['type5']);
		$type6 = mysqli_real_escape_string($condb,$_POST['type6']);
		$type7 = mysqli_real_escape_string($condb,$_POST['type7']);
		$type8 = mysqli_real_escape_string($condb,$_POST['type8']);
		$type9 = mysqli_real_escape_string($condb,$_POST['type9']);
		$type10 = mysqli_real_escape_string($condb,$_POST['type10']);
		$type11 = mysqli_real_escape_string($condb,$_POST['type11']);
		$type12 = mysqli_real_escape_string($condb,$_POST['type12']);
		$type13 = mysqli_real_escape_string($condb,$_POST['type13']);
		$type14 = mysqli_real_escape_string($condb,$_POST['type14']);
		$type15 = mysqli_real_escape_string($condb,$_POST['type15']);
		$type16 = mysqli_real_escape_string($condb,$_POST['type16']);
		$type17 = mysqli_real_escape_string($condb,$_POST['type17']);
		$type18 = mysqli_real_escape_string($condb,$_POST['type18']);
		$type19 = mysqli_real_escape_string($condb,$_POST['type19']);
		$type20 = mysqli_real_escape_string($condb,$_POST['type20']);
		$type21 = mysqli_real_escape_string($condb,$_POST['type21']);
		$type22 = mysqli_real_escape_string($condb,$_POST['type22']);
		$type23 = mysqli_real_escape_string($condb,$_POST['type23']);
		$type24 = mysqli_real_escape_string($condb,$_POST['type24']);
		$type25 = mysqli_real_escape_string($condb,$_POST['type25']);
		$type26 = mysqli_real_escape_string($condb,$_POST['type26']);
		$type27 = mysqli_real_escape_string($condb,$_POST['type27']);
		$type28 = mysqli_real_escape_string($condb,$_POST['type28']);
		$type29 = mysqli_real_escape_string($condb,$_POST['type29']);
		$type30 = mysqli_real_escape_string($condb,$_POST['type30']);
		$type31 = mysqli_real_escape_string($condb,$_POST['type31']);
		$type32 = mysqli_real_escape_string($condb,$_POST['type32']);
		$type33 = mysqli_real_escape_string($condb,$_POST['type33']);
		$type34 = mysqli_real_escape_string($condb,$_POST['type34']);
		$type35 = mysqli_real_escape_string($condb,$_POST['type35']);
		$type36 = mysqli_real_escape_string($condb,$_POST['type36']);
		$type37 = mysqli_real_escape_string($condb,$_POST['type37']);
		$type38 = mysqli_real_escape_string($condb,$_POST['type38']);
		$type39 = mysqli_real_escape_string($condb,$_POST['type39']);
		$type40 = mysqli_real_escape_string($condb,$_POST['type40']);
		$type41 = mysqli_real_escape_string($condb,$_POST['type41']);
		$type42 = mysqli_real_escape_string($condb,$_POST['type42']);
		$type43 = mysqli_real_escape_string($condb,$_POST['type43']);
		$type44 = mysqli_real_escape_string($condb,$_POST['type44']);
		$type45 = mysqli_real_escape_string($condb,$_POST['type45']);
		$type46 = mysqli_real_escape_string($condb,$_POST['type46']);
		$type47 = mysqli_real_escape_string($condb,$_POST['type47']);
		$type48 = mysqli_real_escape_string($condb,$_POST['type48']);
		$type49 = mysqli_real_escape_string($condb,$_POST['type49']);
		$type50 = mysqli_real_escape_string($condb,$_POST['type50']);
		$type51 = mysqli_real_escape_string($condb,$_POST['type51']);
		$type52 = mysqli_real_escape_string($condb,$_POST['type52']);
		$type53 = mysqli_real_escape_string($condb,$_POST['type53']);
		$type54 = mysqli_real_escape_string($condb,$_POST['type54']);
		$type55 = mysqli_real_escape_string($condb,$_POST['type55']);
		$type56 = mysqli_real_escape_string($condb,$_POST['type56']);
		$type57 = mysqli_real_escape_string($condb,$_POST['type57']);
		$type58 = mysqli_real_escape_string($condb,$_POST['type58']);
		$type59 = mysqli_real_escape_string($condb,$_POST['type59']);
		$type60 = mysqli_real_escape_string($condb,$_POST['type60']);
		$type61 = mysqli_real_escape_string($condb,$_POST['type61']);
		$type62 = mysqli_real_escape_string($condb,$_POST['type62']);
		$type63 = mysqli_real_escape_string($condb,$_POST['type63']);
		$type64 = mysqli_real_escape_string($condb,$_POST['type64']);
		$type65 = mysqli_real_escape_string($condb,$_POST['type65']);
		$type65 = mysqli_real_escape_string($condb,$_POST['type65']);
		$type67 = mysqli_real_escape_string($condb,$_POST['type67']);
		$type68 = mysqli_real_escape_string($condb,$_POST['type68']);
		$type69 = mysqli_real_escape_string($condb,$_POST['type69']);
		$type70 = mysqli_real_escape_string($condb,$_POST['type70']);
		$type71 = mysqli_real_escape_string($condb,$_POST['type71']);
		$type72 = mysqli_real_escape_string($condb,$_POST['type72']);
		$type73 = mysqli_real_escape_string($condb,$_POST['type73']);
		$type74 = mysqli_real_escape_string($condb,$_POST['type74']);
		$type75 = mysqli_real_escape_string($condb,$_POST['type75']);
		$type76 = mysqli_real_escape_string($condb,$_POST['type76']);
		$type77 = mysqli_real_escape_string($condb,$_POST['type77']);
		$type78 = mysqli_real_escape_string($condb,$_POST['type78']);
		$type79 = mysqli_real_escape_string($condb,$_POST['type79']);
		$type80 = mysqli_real_escape_string($condb,$_POST['type80']);
		$type81 = mysqli_real_escape_string($condb,$_POST['type81']);
		$type82 = mysqli_real_escape_string($condb,$_POST['type82']);
		$type83 = mysqli_real_escape_string($condb,$_POST['type83']);
		$type84 = mysqli_real_escape_string($condb,$_POST['type84']);
		$type85 = mysqli_real_escape_string($condb,$_POST['type85']);
		$type86 = mysqli_real_escape_string($condb,$_POST['type86']);
		$type87 = mysqli_real_escape_string($condb,$_POST['type87']);
		$type88 = mysqli_real_escape_string($condb,$_POST['type88']);
		$type89 = mysqli_real_escape_string($condb,$_POST['type89']);
		$type90 = mysqli_real_escape_string($condb,$_POST['type90']);
		$type91 = mysqli_real_escape_string($condb,$_POST['type91']);
		$type92 = mysqli_real_escape_string($condb,$_POST['type92']);
		$type93 = mysqli_real_escape_string($condb,$_POST['type93']);
		$type94 = mysqli_real_escape_string($condb,$_POST['type94']);
		$type95 = mysqli_real_escape_string($condb,$_POST['type95']);
		$type96 = mysqli_real_escape_string($condb,$_POST['type96']);
		$type97 = mysqli_real_escape_string($condb,$_POST['type97']);
		$type98 = mysqli_real_escape_string($condb,$_POST['type98']);
		$type99 = mysqli_real_escape_string($condb,$_POST['type99']);
		
	
	$meSql = "UPDATE payslip SET salary='".$salary."',tax='".$tax."',assur_dd='".$assur_dd."',saving='".$saving."',kid='".$kid."',gpf='".$gpf."',pfund='".$pfund."',soc='".$soc."',total='".$total."',type1='".$type1."',type2='".$type2."',type3='".$type3."',type4='".$type4."',type5='".$type5."',type6='".$type7."',type8='".$type8."',type9='".$type9."',type10='".$type10."',type11='".$type11."',type12='".$type12."',type13='".$type13."',type14='".$type14."',type15='".$type15."',type16='".$type16."',type17='".$type17."',type18='".$type18."',type19='".$type19."',type20='".$type20."',type21='".$type21."',type22='".$type22."',type23='".$type23."',type24='".$type24."',type25='".$type25."',type26='".$type26."',type27='".$type27."',type28='".$type28."',type29='".$type29."',type30='".$type30."',type31='".$type31."',type32='".$type32."',type33='".$type33."',type34='".$type34."',type35='".$type35."',type36='".$type36."',type37='".$type37."',type38='".$type38."',type39='".$type39."',type40='".$type40."',type41='".$type41."',type42='".$type42."',type43='".$type43."',type44='".$type44."',type45='".$type45."',type46='".$type46."',type47='".$type47."',type48='".$type48."',type49='".$type49."',type50='".$type50."',type51='".$type51."',type52='".$type52."',type53='".$type53."',type54='".$type54."',type55='".$type55."',type56='".$type56."',type57='".$type57."',type58='".$type58."',type59='".$type59."',type60='".$type60."',type61='".$type61."',type62='".$type62."',type63='".$type63."',type64='".$type64."',type65='".$type65."',type66='".$type66."',type67='".$type67."',type68='".$type68."',type69='".$type69."',type70='".$type70."',type71='".$type71."',type72='".$type72."',type73='".$type73."',type74='".$type74."',type75='".$type75."',type76='".$type76."',type77='".$type77."',type78='".$type78."',type79='".$type79."',type80='".$type80."',type81='".$type81."',type82='".$type82."',type83='".$type83."',type84='".$type84."',type85='".$type85."',type86='".$type86."',type87='".$type87."',type88='".$type88."',type89='".$type89."',type90='".$type90."',type91='".$type91."',type92='".$type92."',type93='".$type93."',type94='".$type94."',type95='".$type95."',type96='".$type96."',type97='".$type97."',type98='".$type98."',type99='".$type99."' where id_num = '".$id_num."' ";
		$meQeury = mysqli_query($condb,$meSql);
		
		header("location:data_admin.php");


mysqli_close($condb);
?>